additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: dynamic.opentlc.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: khm8m
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr:  192.168.160.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIPs:
    - 192.168.160.201
    failureDomains:
    - name: generated-failure-domain
      region: generated-region
      server: portal.vc.opentlc.com
      topology:
        computeCluster: /SDDC-Datacenter/host/Cluster-1
        datacenter: SDDC-Datacenter
        datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
        networks:
        - segment-sandbox-khm8m
        resourcePool: /SDDC-Datacenter/host/Cluster-1//Resources
      zone: generated-zone
    ingressVIPs:
    - 192.168.160.202
    vcenters:
    - datacenters:
      - SDDC-Datacenter
      password: ...
      port: 443
      server: portal.vc.opentlc.com
      user: ...
publish: External
pullSecret: ...
sshKey: |
  ssh-ed25519 ... 
