apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-cluster-init-bundle
  namespace: rhacs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-cluster-init-bundle
subjects:
- kind: ServiceAccount
  name: create-cluster-init-bundle
  namespace: rhacs-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-cluster-init-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "1"