apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-cluster-init-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete